spring.application.name=user-service
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=never
app.service-name=user-service
app.private-key=${SERVICE_PRIVATE_KEY}
app.user-public-key=${USER_PUBLIC_KEY}
app.product-public-key=${PRODUCT_PUBLIC_KEY}
app.trade-public-key=${TRADE_PUBLIC_KEY}
app.user-url=${USER_SERVICE_URL:http://user-service:8080}
app.product-url=${PRODUCT_SERVICE_URL:http://product-service:8080}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=readinessState,db
management.endpoint.health.show-details=never
server.error.include-message=never
