ALTER TABLE orders ADD COLUMN list_price_cent INT, ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE offers MODIFY status ENUM('ACCEPTED','ACCEPTING','CANCELLED','PENDING','REJECTED') NOT NULL, ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE after_sale_requests ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE shipments ADD UNIQUE KEY uk_shipment_order(order_id);
CREATE TABLE payments(payment_no VARCHAR(64) PRIMARY KEY,order_id BIGINT NOT NULL UNIQUE,buyer_id BIGINT NOT NULL,amount_cent INT NOT NULL,status VARCHAR(20) NOT NULL,refunded_cent INT NOT NULL DEFAULT 0,method VARCHAR(20),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE refunds(refund_no VARCHAR(64) PRIMARY KEY,after_sale_id BIGINT NOT NULL UNIQUE,order_id BIGINT NOT NULL,amount_cent INT NOT NULL,created_at DATETIME NOT NULL);
